server:
  port: 8888
  name: /
  servlet:
     session:
        timeout: 1800s
  
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/pinellia?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大 
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      filters: stat
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 2
   jpa:
      show-sql: false
      hibernate:
         #ddl-auto: update
         show-sql: false
         naming:
            #用于解决 jpa 在解析实体类的Cloumn的时候驼峰命名时，大写字母自动转为下划线加小写字母问题
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            #系统使用hibernate查询，这里配置session的控制交给hibernate
            current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
   resources:
      static-locations: classpath:/static/pinellia-web/
#   mvc:
#      static-path-pattern: /tc-web/**
#   thymeleaf:
#      prefix: classpath:/static/tc-web/html/
#      suffix: .html